PLAYERS = [
    {
        "_id": "110",
        "first_name": "Kobe",
        "last_name": "Bryant",
        "birthday": "08-23-1978",
        "start_year": "1997",
        "end_year": "2016",
        "image_url": "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/110.png",
    },
    {
        "_id": "1966",
        "first_name": "LeBron",
        "last_name": "James",
        "birthday": "12-30-1984",
        "start_year": "2004",
        "end_year": None,
        "image_url": "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/1966.png",
    },
    {
        "_id": "6583",
        "first_name": "Anthony",
        "last_name": "Davis",
        "birthday": "03-11-1993",
        "start_year": "2013",
        "end_year": None,
        "image_url": "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/6583.png",
    },
    {
        "_id": "3945274",
        "first_name": "Luka",
        "last_name": "Doncic",
        "birthday": "02-28-1999",
        "start_year": "2019",
        "end_year": None,
        "image_url": "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3945274.png",
    },
    {
        "_id": "3032977",
        "first_name": "Giannis",
        "last_name": "Antetokounmpo",
        "birthday": "12-06-1994",
        "start_year": "2014",
        "end_year": None,
        "image_url": "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3032977.png",
    },
    {
        "_id": "3975",
        "first_name": "Stephen",
        "last_name": "Curry",
        "birthday": "03-14-1988",
        "start_year": "2010",
        "end_year": None,
        "image_url": "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3975.png",
    },
]
